### ISSUE TITLE
Fix morph() to morph instead of replace

### ISSUE THREAD

**Issue by connorwbey** [marcoroth/turbo-morph#1]
## What?
morph() replaces instead of morphs.
## Why?
Due to templateContent() returning a DocumentFragment and morphdom not working right with a DocumentFragment. It replaces instead of diffing and morphing like it should.
## How?
Pass in a ternary for the new element that if childrenOnly is true passes `this.templateContent`, else passes `this.templateElement.innerHTML`. This keeps childrenOnly working as it has no problem with a DocumentFragment but does not work with `this.templateElement.innerHTML`. And for regular morphs they diff and morph correctly with `this.templateElement.innerHTML` where [templateElement()](https://github.com/hotwired/turbo/blob/e30d36bf56d020d63d87a8350d9d0361edd9b804/src/elements/stream_element.ts#L109) gets the the template element and innerHTML for the html.

This had come up in the CableReady repo: [#58](https://github.com/stimulusreflex/cable_ready/pull/58) [#67](https://github.com/stimulusreflex/cable_ready/issues/67)

**Comment by marcoroth** [comment]
Fixed via #2, thanks @connorwbey!
