### ISSUE TITLE
See hotwired/turbo#684

### ISSUE THREAD

**Issue by seanpdoyle** [marcoroth/turbo-morph#3]
I've opened https://github.com/hotwired/turbo/pull/684, which changes the way that custom actions are defined from directly accessing `StreamActions` to defining a `turbo:before-stream-render` event listener.

If that change ships before a `7.2.0` release, this package will need to change how its morphdom integration is defined.

**Comment by marcoroth** [comment]
Thank you for the heads-up!

**Comment by drnic** [comment]
Is this issue related to this error I'm seeing?

```
js     | ✘ [ERROR] No matching export in "../../node_modules/@hotwired/turbo/dist/turbo.es2017-esm.js" for import "StreamActions"
js     |
js     |     ../../node_modules/turbo-morph/dist/index.js:1:7:
js     |       1 │ import{StreamActions as e}from"@hotwired/turbo";var t;var n="undefi...
js     |         ╵        ~~~~~~~~~~~~~
js     |
js     | /Users/drnic/Projects/insurance-policies/insurance-policies/node_modules/esbuild/lib/main.js:1624
js     |   let error = new Error(`${text}${summary}`);
js     |               ^
js     |
js     | Error: Build failed with 1 error:
js     | ../../node_modules/turbo-morph/dist/index.js:1:7: ERROR: No matching export in "../../node_modules/@hotwired/turbo/dist/turbo.es2017-esm.js" for import "StreamActions"
```

I've on turbo-rails 7.1.3 / turbo 7.1.0.

**Comment by drnic** [comment]
Ah, I see in the readme that I need to wait for turbo 7.2.0.

**Comment by marcoroth** [comment]
I think we can close this one since Turbo 7.2 ships with the `StreamActions` export and the `turbo:before-stream-render` event listener.
